language: cpp

jobs:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - cppcheck
            
script:
  - cppcheck --enable=all --error-exitcode=1 --inconclusive main.cc purrito.cc
