language: cpp

jobs:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 CXX=g++-7"
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 CXX=g++-8"
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 CXX=g++-9"

    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-7
      env:
        - MATRIX_EVAL="CC=clang-7 CXX=clang++-7"
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-8
      env:
        - MATRIX_EVAL="CC=clang-8 CXX=clang++-8"
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
      env:
        - MATRIX_EVAL="CC=clang-9 CXX=clang++-9"
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-10
      env:
        - MATRIX_EVAL="CC=clang-10 CXX=clang++-10"

    - os: osx
      osx_image: xcode7.3
      env:
        - MATRIX_EVAL="CC=clang CXX=clang++"
    - os: osx
      osx_image: xcode8.3
      env:
        - MATRIX_EVAL="CC=clang CXX=clang++"
    - os: osx
      osx_image: xcode9.4
      env:
        - MATRIX_EVAL="CC=clang CXX=clang++"
    - os: osx
      osx_image: xcode10.3
      env:
        - MATRIX_EVAL="CC=clang CXX=clang++"
    - os: osx
      osx_image: xcode11.3
      env:
        - MATRIX_EVAL="CC=clang CXX=clang++"

before_script:
  - eval "${MATRIX_EVAL}"


install:
  - export PYTHONUSERBASE=~/.loc9
  - easy_install --user scan-build
  - easy_install --user typing

script:
  - cppcheck --enable=all --error-exitcode=1 --inconclusive main.cc purrito.cc
  - make
  - scan-build --status-bugs make -B
