name: pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 */6 * * *'

env:
  CC: gcc-10
  CXX: g++-10

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get install -y libssl-dev pkg-config gcc-10 g++-10 mandoc valgrind llvm
    - name: Install uSockets
      run: |
        git clone https://github.com/uNetworking/uSockets
        wget https://raw.githubusercontent.com/gentoo/guru/dev/net-libs/usockets/files/usockets-0.7.1-Makefile.patch
        cd uSockets
        git apply < ../usockets-0.7.1-Makefile.patch
        make WITH_OPENSSL=1
        sudo make install
    - name: Install uWebSockets
      run: |
        git clone https://github.com/uNetworking/uWebSockets
        cd uWebSockets
        sudo cp -r src /usr/include/uWebSockets
    - name: Make
      run: |
        scan-build make
    - name: Test
      run: |
        env GH_ACTIONS="YES" P_CONCUR=5 P_MAXSIZE=3 PURRITO="valgrind --leak-check=full --show-leak-kinds=all --verbose ../purrito" --error-exitcode=1 make check
    - name: Check man pages
      run: |
        mandoc -T lint -W warning man/purrito.1
