name: pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 */6 * * *'

env:
  CC: gcc-10
  CXX: g++-10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        sudo apt update
        sudo apt-get install -y libssl-dev pkg-config gcc-10 g++-10
    - name: Install uSockets
      run: |
        echo $(pwd)
        git clone https://github.com/uNetworking/uSockets
        wget https://raw.githubusercontent.com/gentoo/guru/dev/net-libs/usockets/files/usockets-0.7.1-Makefile.patch
        cd uSockets
        git apply < ../usockets-0.7.1-Makefile.patch
        make WITH_OPENSSL=1
        sudo make install
    - name: Install uWebSockets
      run: |
        echo $(pwd)
        git clone https://github.com/uNetworking/uWebSockets
        cd uWebSockets
        sudo cp -r src /usr/include/uWebSockets
    - name: Make
      run: |
        make
    - name: Test
      run: |
        env GH_ACTIONS="YES" P_CONCUR=5 P_MAXSIZE=3 make check
